//! Main plugin entry point for **Nebula Stereo Delay** by Nebula Audio.
//!
//! This crate implements a professional stereo delay audio plugin built on
//! [nih-plug](https://github.com/robbert-vdh/nih-plug). It exports both
//! CLAP and VST3 plugin formats (AUv2 is generated at build time via the
//! free-audio/clap-wrapper).
//!
//! # Architecture
//!
//! ```text
//! ┌──────────────────────────────────────────────────────────────────┐
//! │                      NebulaStereoDelay                          │
//! │                                                                  │
//! │  params: Arc<NebulaStereoDelayParams>  ◄── shared with GUI      │
//! │  engine: DelayEngine                   ◄── f64 DSP core         │
//! │  state_manager: StateManager           ◄── meters + spectrum    │
//! │  midi_cc: MidiCcValues                 ◄── lock-free CC store   │
//! │  preset_manager: PresetManager         ◄── factory + user banks │
//! │  sample_rate: f64                      ◄── current host SR      │
//! │                                                                  │
//! │  process() flow per sample:                                      │
//! │    host f32 → f64 → DelayEngine → f64 → denormal flush → f32   │
//! └──────────────────────────────────────────────────────────────────┘
//! ```
//!
//! # Signal Flow (per sample)
//!
//! 1. Read smoothed parameter values from [`NebulaStereoDelayParams`].
//! 2. Build a [`dsp::DelayParams`] struct (f32 → f64 conversion).
//! 3. Pass input samples through [`DelayEngine::process()`] in f64.
//! 4. Flush denormal numbers to zero (prevents CPU spikes).
//! 5. Convert output back to f32 for the host buffer.
//! 6. Update lock-free peak meters via [`StateManager`].
//!
//! # Plugin Formats
//!
//! | Format   | Export Macro                     | Platform             |
//! |----------|----------------------------------|----------------------|
//! | CLAP     | `nih_export_clap!`               | Linux, macOS, Windows|
//! | VST3     | `nih_export_vst3!`               | Linux, macOS, Windows|
//! | AUv2     | Generated by clap-wrapper at build| macOS only           |

/// DSP engine — always available (no plugin dependency).
pub mod dsp;

#[cfg(feature = "plugin")]
pub mod gui;
#[cfg(feature = "plugin")]
pub mod midi;
#[cfg(feature = "plugin")]
pub mod parameters;
#[cfg(feature = "plugin")]
pub mod preset;
#[cfg(feature = "plugin")]
pub mod state;

// ──────────────────────────────────────────────────────────────────────────
// Everything below requires the "plugin" feature (nih_plug, GUI, etc.)
// ──────────────────────────────────────────────────────────────────────────

#[cfg(feature = "plugin")]
use std::sync::atomic::Ordering;
#[cfg(feature = "plugin")]
use std::sync::Arc;

#[cfg(feature = "plugin")]
use nih_plug::params::Param;
#[cfg(feature = "plugin")]
use nih_plug::prelude::*;

#[cfg(feature = "plugin")]
use crate::dsp::DelayEngine;
#[cfg(feature = "plugin")]
use crate::midi::MidiCcValues;
#[cfg(feature = "plugin")]
use crate::parameters::NebulaStereoDelayParams;
#[cfg(feature = "plugin")]
use crate::preset::PresetManager;
#[cfg(feature = "plugin")]
use crate::state::StateManager;

#[cfg(feature = "plugin")]
const DENORMAL_THRESHOLD_F64: f64 = 1e-30;
#[cfg(feature = "plugin")]
const DENORMAL_THRESHOLD_F32: f32 = 1e-30;
#[cfg(feature = "plugin")]
const DEFAULT_TEMPO_BPM: f64 = 120.0;

#[cfg(feature = "plugin")]
#[inline(always)]
fn flush_denormal_f64(x: f64) -> f64 {
    if x.abs() < DENORMAL_THRESHOLD_F64 {
        0.0
    } else {
        x
    }
}

#[cfg(feature = "plugin")]
#[inline(always)]
fn flush_denormal_f32(x: f32) -> f32 {
    if x.abs() < DENORMAL_THRESHOLD_F32 {
        0.0
    } else {
        x
    }
}

#[cfg(feature = "plugin")]
pub struct NebulaStereoDelay {
    params: Arc<NebulaStereoDelayParams>,
    engine: DelayEngine,
    state_manager: StateManager,
    midi_cc: MidiCcValues,
    preset_manager: PresetManager,
    sample_rate: f64,
}

#[cfg(feature = "plugin")]
impl Default for NebulaStereoDelay {
    fn default() -> Self {
        let params = Arc::new(NebulaStereoDelayParams::default());
        let sample_rate = 44_100.0;

        Self {
            state_manager: StateManager::new(params.clone()),
            engine: DelayEngine::new(sample_rate),
            params,
            midi_cc: MidiCcValues::new(),
            preset_manager: PresetManager::new(),
            sample_rate,
        }
    }
}

#[cfg(feature = "plugin")]
impl Plugin for NebulaStereoDelay {
    const NAME: &'static str = "Nebula Stereo Delay";
    const VENDOR: &'static str = "Nebula Audio";
    const URL: &'static str = "";
    const EMAIL: &'static str = "";
    const VERSION: &'static str = "1.0.0";

    const DEFAULT_INPUT_CHANNELS: u32 = 2;
    const DEFAULT_OUTPUT_CHANNELS: u32 = 2;
    const SAMPLE_ACCURATE_AUTOMATION: bool = true;

    type SysExMessage = ();
    type BackgroundTask = ();

    fn params(&self) -> Arc<dyn Params> {
        self.params.clone()
    }

    fn editor(&mut self, _async_executor: AsyncExecutor<Self>) -> Option<Box<dyn Editor>> {
        gui::create_egui_editor(self.params.clone())
    }

    fn initialize(
        &mut self,
        _bus_config: &BusConfig,
        buffer_config: &BufferConfig,
        _context: &mut InitContext<Self>,
    ) -> bool {
        self.sample_rate = buffer_config.sample_rate as f64;
        self.engine = DelayEngine::new(self.sample_rate);
        self.engine.reset();
        self.state_manager = StateManager::new(self.params.clone());
        true
    }

    fn process(
        &mut self,
        buffer: &mut Buffer,
        _aux: &mut AuxBuffers,
        context: &mut ProcessContext<Self>,
    ) -> ProcessStatus {
        let transport = context.transport();
        let tempo_bpm = if transport.tempo > 0.0 {
            transport.tempo as f64
        } else {
            DEFAULT_TEMPO_BPM
        };

        let soft_bypass = self.params.bypass.load(Ordering::Relaxed);
        self.engine.set_bypass(soft_bypass);

        while let Some(event) = context.next_event() {
            match event {
                NoteEvent::MidiEvent {
                    timing: _,
                    midi_data,
                } => {
                    let status = midi_data[0];
                    if (0xB0..=0xBF).contains(&status) {
                        let channel = status & 0x0F;
                        let cc = midi_data[1] & 0x7F;
                        let value = midi_data[2] & 0x7F;
                        let normalized = value as f32 / 127.0;
                        self.midi_cc.set(channel, cc, normalized);
                    }
                }
                _ => {}
            }
        }

        self.apply_midi_cc();

        let input_mode_l = self.params.input_mode_l.value().into();
        let input_mode_r = self.params.input_mode_r.value().into();
        let feedback_phase_l = self.params.feedback_phase_l.value();
        let feedback_phase_r = self.params.feedback_phase_r.value();
        let crossfeed_phase = self.params.crossfeed_phase.value();
        let routing = self.params.routing.value().into();
        let tempo_sync = self.params.tempo_sync.value();
        let note_l = self.params.note_l.value().into();
        let note_r = self.params.note_r.value().into();
        let halve_l = self.params.halve_l.value();
        let halve_r = self.params.halve_r.value();
        let double_l = self.params.double_l.value();
        let double_r = self.params.double_r.value();
        let stereo_link = self.params.stereo_link.value();

        for mut sample in buffer.iter_samples() {
            let delay_params = dsp::DelayParams {
                input_mode_l,
                input_mode_r,
                delay_time_l: self.params.delay_time_l.smoothed.next() as f64,
                delay_time_r: self.params.delay_time_r.smoothed.next() as f64,
                low_cut_l: self.params.low_cut_l.smoothed.next() as f64,
                low_cut_r: self.params.low_cut_r.smoothed.next() as f64,
                high_cut_l: self.params.high_cut_l.smoothed.next() as f64,
                high_cut_r: self.params.high_cut_r.smoothed.next() as f64,
                feedback_l: self.params.feedback_l.smoothed.next() as f64,
                feedback_r: self.params.feedback_r.smoothed.next() as f64,
                feedback_phase_l,
                feedback_phase_r,
                crossfeed_lr: self.params.crossfeed_lr.smoothed.next() as f64,
                crossfeed_rl: self.params.crossfeed_rl.smoothed.next() as f64,
                crossfeed_phase,
                routing,
                tempo_sync,
                tempo_bpm,
                note_l,
                note_r,
                deviation_l: self.params.deviation_l.smoothed.next() as f64,
                deviation_r: self.params.deviation_r.smoothed.next() as f64,
                halve_l,
                halve_r,
                double_l,
                double_r,
                output_mix_l: self.params.output_mix_l.smoothed.next() as f64,
                output_mix_r: self.params.output_mix_r.smoothed.next() as f64,
                bypass: soft_bypass,
                stereo_link,
            };

            let in_l = sample[0] as f64;
            let in_r = sample[1] as f64;

            let (out_l, out_r) = self.engine.process(in_l, in_r, &delay_params);

            let out_l = flush_denormal_f64(out_l);
            let out_r = flush_denormal_f64(out_r);

            let out_l_f32 = flush_denormal_f32(out_l as f32);
            let out_r_f32 = flush_denormal_f32(out_r as f32);

            sample[0] = out_l_f32;
            sample[1] = out_r_f32;

            self.state_manager
                .update_meters(out_l_f32, out_r_f32, 0.0, 0.0);
        }

        ProcessStatus::Normal
    }
}

#[cfg(feature = "plugin")]
impl NebulaStereoDelay {
    fn apply_midi_cc(&self) {
        if let Ok(midi_learn) = self.params.midi_learn.try_read() {
            for mapping in &midi_learn.mappings {
                if let Some(normalized) = self.midi_cc.get_and_clear(mapping.channel, mapping.cc) {
                    self.set_param_normalized(&mapping.param_id, normalized);
                }
            }
        }
    }

    fn set_param_normalized(&self, id: &str, normalized: f32) {
        match id {
            "iml" => self.params.input_mode_l.set_normalized_value(normalized),
            "imr" => self.params.input_mode_r.set_normalized_value(normalized),
            "dtl" => self.params.delay_time_l.set_normalized_value(normalized),
            "dtr" => self.params.delay_time_r.set_normalized_value(normalized),
            "ntl" => self.params.note_l.set_normalized_value(normalized),
            "ntr" => self.params.note_r.set_normalized_value(normalized),
            "dvl" => self.params.deviation_l.set_normalized_value(normalized),
            "dvr" => self.params.deviation_r.set_normalized_value(normalized),
            "hvl" => self.params.halve_l.set_normalized_value(normalized),
            "hvr" => self.params.halve_r.set_normalized_value(normalized),
            "dbl" => self.params.double_l.set_normalized_value(normalized),
            "dbr" => self.params.double_r.set_normalized_value(normalized),
            "lcl" => self.params.low_cut_l.set_normalized_value(normalized),
            "lcr" => self.params.low_cut_r.set_normalized_value(normalized),
            "hcl" => self.params.high_cut_l.set_normalized_value(normalized),
            "hcr" => self.params.high_cut_r.set_normalized_value(normalized),
            "fbl" => self.params.feedback_l.set_normalized_value(normalized),
            "fbr" => self.params.feedback_r.set_normalized_value(normalized),
            "fpl" => self.params.feedback_phase_l.set_normalized_value(normalized),
            "fpr" => self.params.feedback_phase_r.set_normalized_value(normalized),
            "clr" => self.params.crossfeed_lr.set_normalized_value(normalized),
            "crl" => self.params.crossfeed_rl.set_normalized_value(normalized),
            "cfp" => self.params.crossfeed_phase.set_normalized_value(normalized),
            "rout" => self.params.routing.set_normalized_value(normalized),
            "tsyn" => self.params.tempo_sync.set_normalized_value(normalized),
            "slnk" => self.params.stereo_link.set_normalized_value(normalized),
            "oml" => self.params.output_mix_l.set_normalized_value(normalized),
            "omr" => self.params.output_mix_r.set_normalized_value(normalized),
            _ => {}
        }
    }
}

#[cfg(feature = "plugin")]
nih_plug::nih_export_clap!(NebulaStereoDelay);

#[cfg(feature = "plugin")]
nih_plug::nih_export_vst3!(NebulaStereoDelay);
